package adaptivelearning.module.planner.controller;
import adaptivelearning.config.response.*; import adaptivelearning.module.planner.dto.request.*; import adaptivelearning.module.planner.dto.response.*; import adaptivelearning.module.planner.service.PlannerService; import adaptivelearning.utils.*; import io.swagger.v3.oas.annotations.tags.Tag; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.List;
@RestController @RequestMapping(ClientUtils.VERSION+"/plans") @RequiredArgsConstructor @Tag(name="Study Planner") @PreAuthorize("isAuthenticated()")
public class PlannerController {
    private final PlannerService service;
    @PostMapping public ResponseEntity<DefaultRes<StudyPlanResponse>> create(@Valid @RequestBody CreatePlanRequest r){ return ResponseEntity.status(HttpStatus.CREATED).body(DefaultRes.res(StatusCode.CREATED,"Plan created",service.createPlan(SecurityUtils.getCurrentUserId(),r))); }
    @GetMapping public DefaultRes<List<StudyPlanResponse>> list(){ return DefaultRes.res(StatusCode.OK,"Plans retrieved",service.listPlans(SecurityUtils.getCurrentUserId())); }
    @GetMapping("/{id}") public DefaultRes<StudyPlanResponse> get(@PathVariable Long id){ return DefaultRes.res(StatusCode.OK,"Plan retrieved",service.getPlan(SecurityUtils.getCurrentUserId(),id)); }
    @GetMapping("/{id}/summary") public DefaultRes<PlanSummaryResponse> summary(@PathVariable Long id){ StudyPlanResponse p=service.getPlan(SecurityUtils.getCurrentUserId(),id); var tasks=service.generateDefaultTasks(id); long done=tasks.stream().filter(t->"COMPLETED".equals(t.getStatus().name())).count(); long overdue=tasks.stream().filter(t->t.getScheduledDate()!=null && t.getScheduledDate().isBefore(java.time.LocalDate.now()) && t.getStatus().name().equals("PENDING")).count(); int upcoming=(int)tasks.stream().filter(t->t.getScheduledDate()!=null && !t.getScheduledDate().isBefore(java.time.LocalDate.now())).count(); double progress=tasks.isEmpty()?0: done*100.0/tasks.size(); String dist=tasks.stream().collect(java.util.stream.Collectors.groupingBy(PlanTaskResponse::getSkill, java.util.stream.Collectors.counting())).toString(); return DefaultRes.res(StatusCode.OK,"Summary",PlanSummaryResponse.builder().planId(id).title(p.getTitle()).progressPercent(progress).overdueCount(overdue).upcomingTasks(upcoming).skillDistributionJson(dist).build()); }
    @PatchMapping("/tasks/{taskId}") public DefaultRes<PlanTaskResponse> updateTask(@PathVariable Long taskId, @Valid @RequestBody UpdateTaskRequest r){ return DefaultRes.res(StatusCode.OK,"Task updated",service.updateTask(taskId,r)); }
    @PostMapping("/{id}/complete") public DefaultRes<StudyPlanResponse> complete(@PathVariable Long id){ return DefaultRes.res(StatusCode.OK,"Plan completed",service.completePlan(SecurityUtils.getCurrentUserId(),id)); }
    @PostMapping("/{id}/archive") public DefaultRes<StudyPlanResponse> archive(@PathVariable Long id){ return DefaultRes.res(StatusCode.OK,"Plan archived",service.archivePlan(SecurityUtils.getCurrentUserId(),id)); }
}
