package adaptivelearning.module.speaking.service.impl;
import adaptivelearning.config.response.*; import adaptivelearning.module.ai.gateway.AiProvider; import adaptivelearning.module.speaking.dto.request.*; import adaptivelearning.module.speaking.dto.response.*; import adaptivelearning.module.speaking.entity.*; import adaptivelearning.module.speaking.repository.*; import adaptivelearning.module.speaking.service.SpeakingService; import com.fasterxml.jackson.databind.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class SpeakingServiceImpl implements SpeakingService {
 private final SpeakingSubmissionRepository submissions; private final SpeakingEvaluationRepository evaluations; private final AiProvider aiProvider; private final ObjectMapper mapper;
 public SpeakingSubmissionResponse submit(Long uid,SpeakingSubmissionRequest r){ SpeakingSubmission s=SpeakingSubmission.builder().attemptId(r.getAttemptId()).userId(uid).questionId(r.getQuestionId()).transcriptText(r.getTranscriptText()).build(); return to(submissions.save(s)); }
 @Transactional(readOnly=true) public SpeakingSubmissionResponse getSubmission(Long uid,Long id){return to(owned(uid,id));}
 @Transactional(readOnly=true) public List<SpeakingSubmissionResponse> listByAttempt(Long uid,Long aid){return submissions.findByAttemptId(aid).stream().filter(s->s.getUserId().equals(uid)).map(this::to).toList();}
 public SpeakingEvaluationResponse evaluate(Long sid,Long rubricId){ return evaluate(adaptivelearning.utils.SecurityUtils.getCurrentUserId(), sid, rubricId); }
 public SpeakingEvaluationResponse evaluate(Long uid,Long sid,Long rubricId){ SpeakingSubmission s=owned(uid,sid); try { String raw=aiProvider.chatCompletionSync("You are a speaking examiner.","Return JSON with overallScore,criteria,errors,transcript,strengths,rewriteSuggestion,confidence: "+s.getTranscriptText(),"gpt-4o-mini",1200); JsonNode n=mapper.readTree(raw); SpeakingEvaluation e=SpeakingEvaluation.builder().submissionId(sid).questionId(s.getQuestionId()).overallScore(num(n,"overallScore")).criteriaJson(json(n,"criteria")).errorsJson(json(n,"errors")).transcriptJson(json(n,"transcript")).strengthsJson(json(n,"strengths")).rewriteSuggestion(text(n,"rewriteSuggestion")).confidence(num(n,"confidence")).model("gpt-4o-mini").promptVersion("v1.0").build(); s.setStatus(adaptivelearning.shared.enums.SpeakingStatus.GRADED); submissions.save(s); return to(evaluations.save(e)); } catch(Exception e){throw new CommonException(ErrorCode.BAD_REQUEST);} }
 @Transactional(readOnly=true) public List<SpeakingEvaluationResponse> listEvaluations(Long sid){return evaluations.findBySubmissionId(sid).stream().map(this::to).toList();}
 private SpeakingSubmission owned(Long uid,Long id){return submissions.findByIdAndUserId(id,uid).orElseThrow(()->new CommonException(ErrorCode.ENTITY_NOT_FOUND));}
 private Double num(JsonNode n,String k){return n.has(k)&&n.get(k).isNumber()?n.get(k).doubleValue():null;} private String text(JsonNode n,String k){return n.has(k)?n.get(k).asText(null):null;} private String json(JsonNode n,String k){return n.has(k)&&!n.get(k).isNull()?n.get(k).toString():null;}
 private SpeakingSubmissionResponse to(SpeakingSubmission s){return SpeakingSubmissionResponse.builder().submissionId(s.getSubmissionId()).attemptId(s.getAttemptId()).userId(s.getUserId()).questionId(s.getQuestionId()).audioUrl(s.getAudioUrl()).transcriptText(s.getTranscriptText()).durationSeconds(s.getDurationSeconds()).status(s.getStatus()).build();}
 private SpeakingEvaluationResponse to(SpeakingEvaluation e){return SpeakingEvaluationResponse.builder().evaluationId(e.getEvaluationId()).submissionId(e.getSubmissionId()).questionId(e.getQuestionId()).overallScore(e.getOverallScore()).criteriaJson(e.getCriteriaJson()).errorsJson(e.getErrorsJson()).transcriptJson(e.getTranscriptJson()).strengthsJson(e.getStrengthsJson()).rewriteSuggestion(e.getRewriteSuggestion()).confidence(e.getConfidence()).model(e.getModel()).promptVersion(e.getPromptVersion()).build();}
}
