package adaptivelearning.module.contentgen.service.impl;

import adaptivelearning.config.response.*; import adaptivelearning.module.ai.gateway.AiProvider; import adaptivelearning.module.contentgen.dto.request.GenerateQuestionsRequest; import adaptivelearning.module.contentgen.dto.response.ContentGenerationResponse; import adaptivelearning.module.contentgen.entity.ContentGeneration; import adaptivelearning.module.contentgen.repository.ContentGenerationRepository; import adaptivelearning.module.contentgen.service.ContentGenerationService; import adaptivelearning.shared.enums.GenerationStatus;
import com.fasterxml.jackson.databind.*; import java.time.LocalDateTime; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service @RequiredArgsConstructor @Transactional
public class ContentGenerationServiceImpl implements ContentGenerationService {
    private static final String MODEL="gpt-4o-mini"; private final ContentGenerationRepository repo; private final AiProvider ai; private final ObjectMapper mapper;
    public ContentGenerationResponse submit(Long userId, GenerateQuestionsRequest req){ ContentGeneration g=new ContentGeneration(); g.setRequestedBy(userId); g.setCertificateId(req.getCertificateId()); g.setTopicId(req.getTopicId()); g.setGenerationType("QUESTIONS"); g.setPrompt(req.getInstructions()); g.setParametersJson(toString(req)); g.setStatus(GenerationStatus.PENDING); g.setModel(MODEL); g.setItemCount(req.getCount()); ContentGeneration saved=repo.save(g); processOne(saved); return map(saved); }
    @Transactional(readOnly=true) public ContentGenerationResponse get(Long userId,Long id){ ContentGeneration g=repo.findById(id).orElseThrow(()->new CommonException(ErrorCode.ENTITY_NOT_FOUND)); if(!g.getRequestedBy().equals(userId)) throw new CommonException(ErrorCode.FORBIDDEN_ERROR); return map(g); }
    @Transactional(readOnly=true) public List<ContentGenerationResponse> list(Long userId){ return repo.findByRequestedByOrderByCreatedAtDesc(userId).stream().map(this::map).toList(); }
    public ContentGenerationResponse apply(Long id,Long userId){ ContentGeneration g=repo.findById(id).orElseThrow(()->new CommonException(ErrorCode.ENTITY_NOT_FOUND)); if(g.getStatus()!=GenerationStatus.READY) throw new CommonException(ErrorCode.BAD_REQUEST); g.setStatus(GenerationStatus.APPLIED); return map(repo.save(g)); }
    public void processPending(){ repo.findByStatus(GenerationStatus.PENDING).forEach(this::processOne); }
    private void processOne(ContentGeneration g){ g.setStatus(GenerationStatus.PROCESSING); g.setStartedAt(LocalDateTime.now()); repo.save(g); try{ GenerateQuestionsRequest req=fromParameters(g); String system="You generate educational questions. Return ONLY a valid JSON array. Each object MUST have questionType, content, options (array), correctAnswer, explanation. No markdown."; String user="Question type: "+req.getQuestionType()+"\nCount: "+req.getCount()+"\nDifficulty: "+req.getDifficulty()+"\nInstructions: "+req.getInstructions(); String raw=ai.chatCompletionSync(system,user,MODEL,2500); validate(raw); g.setResultJson(raw); g.setStatus(GenerationStatus.READY); g.setItemCount(req.getCount()); }catch(Exception e){ g.setStatus(GenerationStatus.FAILED); g.setErrorMessage(e.getMessage()); } finally { g.setCompletedAt(LocalDateTime.now()); repo.save(g); } }
    private void validate(String raw){ try{ JsonNode n=mapper.readTree(raw); if(!n.isArray()||n.isEmpty()) throw new IllegalArgumentException(); for(JsonNode q:n) for(String f:List.of("questionType","content","options","correctAnswer","explanation")) if(!q.hasNonNull(f)) throw new IllegalArgumentException(); }catch(Exception e){ throw new CommonException(ErrorCode.BAD_REQUEST); } }
    private String toString(GenerateQuestionsRequest r){ try{return mapper.writeValueAsString(r);}catch(Exception e){return "{}";} }
    private GenerateQuestionsRequest fromParameters(ContentGeneration g){ try{return mapper.readValue(g.getParametersJson(),GenerateQuestionsRequest.class);}catch(Exception e){throw new CommonException(ErrorCode.BAD_REQUEST);} }
    private ContentGenerationResponse map(ContentGeneration g){ return ContentGenerationResponse.builder().generationId(g.getGenerationId()).requestedBy(g.getRequestedBy()).certificateId(g.getCertificateId()).topicId(g.getTopicId()).generationType(g.getGenerationType()).prompt(g.getPrompt()).parametersJson(g.getParametersJson()).resultJson(g.getResultJson()).status(g.getStatus()).model(g.getModel()).itemCount(g.getItemCount()).errorMessage(g.getErrorMessage()).startedAt(g.getStartedAt()).completedAt(g.getCompletedAt()).build(); }
}
